module.exports=
{
	LoginData: 
	{
		url:"https://test-int-sapphire.syndigo.com",
		url1:"https://test-int-sapphire.syndigo.com/callback",
		url2:"https://test-int-sapphire.syndigo.com/dashboard",
		username:"veereshamma.kake@syndigo.com",
		password:"VEERU123$",
		title:"Sapphire"
	}
}
